version: '2'
services:
    accumulo-tracer:
        image: quay.io/geodocker/accumulo-geomesa:latest
        network_mode: host
        command: tracer
        environment:
          HADOOP_MASTER_ADDRESS: ${HADOOP_MASTER_ADDRESS}
          ZOOKEEPERS: ${ZOOKEEPERS}
