version: '2'
services:
    accumulo-tserver:
        image: quay.io/geodocker/accumulo-geomesa:latest
        net: host
        command: tserver
        environment:
          HADOOP_MASTER_ADDRESS: ${HADOOP_MASTER_ADDRESS}
          ZOOKEEPERS: ${ZOOKEEPERS}
        