version: '2'
services:
    hdfs-sname:
        image: quay.io/geodocker/hdfs:latest
        net: host
        command: sname
        environment:
          HADOOP_MASTER_ADDRESS: ${HADOOP_MASTER_ADDRESS}