version: '2'
services:
    hdfs-data:
        image: quay.io/geodocker/hdfs:latest
        network_mode: host
        command: data
        environment:
          HADOOP_MASTER_ADDRESS: ${HADOOP_MASTER_ADDRESS}
