version: '2'
services:
    idea:
        image: daunnc/idea:mesatrellis
        environment:
          DISPLAY: *your-hostmachine-ip*:0
        ports:
         # ports for possible local Spark nodes
          - 4050:4040
          - 4051:4041
        # volumes:
        #   - '${PWD}/data/landsat:/data/landsat'
        #   - '${PWD}/target/scala-2.11:/data/jars'
        #   - '${PWD}:/data/project'
